name: Solar-System-Lab

on:
  workflow_dispatch: 
  push:
    branches: 
        - main
        - 'feature/*'

jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        env:
            MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
            MONGO_USERNAME: superuser
            MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        services:
          mongo:
            image: 'siddharth67/mongo-db:non-prod'
       
        steps:
            - name: checkout
              uses: actions/checkout@4

            - name: cache NPM Dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: '${{ runner.os }}-node-modules-${{ hashFiles(''package-lock.json'') }}'

            - name: Install dependencies
              run: npm install

            - name: Unit Testing
              run: npm test

            - name: Archive Test Result
              if: always()
              uses: actions/upload-artifact@v3
              with:
                name: Mocha-Test-result
                path: test-results.xml

