name: Solar-System

on:
  workflow_dispatch: 
  push:
    branches: 
      - main
      - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: superuser
    MONGO_PASSWORD: SuperPassword
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            nodejs-version: [18, 19, 20]
            os: [ubuntu-latest. macos-latest]
            exclude:
              - nodejs-version: 18
                os: macos-latest
        
        runs-on: ${{ matrix.os }}
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4
          
          - name: Setup NodeJs Version - ${{ matrix.nodejs-version }}
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.nodejs-version }}

          - name: Install Dependenicies 
            run: npm install

          - name: Unit Tetsing 
            run: npm test

          - name: Archiving Tets Results
            uses: actions/upload-artifact@v2
            with:
                name: mocha-test-results
                path: test-results.xml
